# Generated by Django 4.0.5 on 2022-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analysis_Model', models.CharField(blank=True, default='novalue', max_length=30)),
                ('ShowWebTab_Model', models.CharField(blank=True, default='novalue', max_length=30)),
                ('SendDateGS_Model', models.CharField(blank=True, default='novalue', max_length=30)),
                ('CreatePlot_Model', models.CharField(blank=True, default='novalue', max_length=30)),
                ('ShowPlot_Model', models.CharField(blank=True, default='novalue', max_length=30)),
            ],
        ),
    ]
