# Generated by Django 4.0.5 on 2022-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnds_mtpltlb', '0002_modelsort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelSort',
        ),
        migrations.AddField(
            model_name='modelaction',
            name='ASC_DESK_1_Model',
            field=models.CharField(default='ASC', max_length=30),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='ASC_DESK_2_Model',
            field=models.CharField(default='ASC', max_length=30),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='ASC_DESK_3_Model',
            field=models.CharField(default='ASC', max_length=30),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='ASC_DESK_4_Model',
            field=models.CharField(default='DESK', max_length=30),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='sorts_1_Model',
            field=models.CharField(default='area', max_length=30),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='sorts_2_Model',
            field=models.CharField(default='cluster', max_length=30),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='sorts_3_Model',
            field=models.CharField(default='cluster_name', max_length=30),
        ),
        migrations.AddField(
            model_name='modelaction',
            name='sorts_4_Model',
            field=models.CharField(default='count', max_length=30),
        ),
    ]
