# Generated by Django 4.0.5 on 2022-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnds_mtpltlb', '0004_modelsort_remove_modelaction_asc_desk_1_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsort',
            old_name='ASC_DESK_1_Model',
            new_name='ASC_DESC_1_Model',
        ),
        migrations.RenameField(
            model_name='modelsort',
            old_name='ASC_DESK_2_Model',
            new_name='ASC_DESC_2_Model',
        ),
        migrations.RenameField(
            model_name='modelsort',
            old_name='ASC_DESK_3_Model',
            new_name='ASC_DESC_3_Model',
        ),
        migrations.RemoveField(
            model_name='modelsort',
            name='ASC_DESK_4_Model',
        ),
        migrations.AddField(
            model_name='modelsort',
            name='ASC_DESC_4_Model',
            field=models.CharField(default='DESC', max_length=30),
        ),
    ]
