# Generated by Django 4.0.5 on 2022-09-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnds_mtpltlb', '0005_rename_asc_desk_1_model_modelsort_asc_desc_1_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsort',
            name='sorts_3_Model',
            field=models.CharField(default='cluster name', max_length=30),
        ),
    ]
