# Generated by Django 4.0.5 on 2022-09-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnds_mtpltlb', '0006_alter_modelsort_sorts_3_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsort',
            name='Sort_Default_Model',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
