# Generated by Django 4.0.5 on 2022-09-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnds_mtpltlb', '0008_alter_modelsort_sort_default_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsort',
            name='Sort_Default_Model',
            field=models.CharField(blank=True, default='novalue', max_length=30),
        ),
    ]
